# Generated by Django 3.0.8 on 2020-07-31 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20200731_0838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingstar',
            options={'verbose_name': 'Звезда рейтинга', 'verbose_name_plural': 'Звезды рейтинга'},
        ),
    ]
